### ISSUE TITLE
Create some original artwork

### ISSUE THREAD

**Issue by JJ** [JJ/2019-concurrent-ea-gecco#12]
Describing now the two communication channels work.

* Channel one receives population and performs several generations on it. It writes result to the "mixer" channel.
* Mixer channel works in pairs. It takes two populations, sends a random one back to itself, sends a new population to channel one.
![threads](https://user-images.githubusercontent.com/500/52266425-aa153480-2936-11e9-98d1-c570b92997d1.jpg)
Something like that, but better drawn. Maybe @mariosky is the best at that, but feel free.

**Comment by mariosky** [comment]
I will do it.

**Comment by JJ** [comment]
Done in 735fc77e0e3d37dca5f28553f50d787378f19d45
