### ISSUE TITLE
Put the paper in GECCO format

### ISSUE THREAD

**Issue by JJ** [JJ/2019-concurrent-ea-gecco#6]
Leave the content for the time being... Please @mariosky can you do that?

**Comment by mariosky** [comment]
Yes, I do it

**Comment by JJ** [comment]
@mariosky you have done it in a different repo :-)
Please keep the .Rnw extension, change name and use the GECCO format.

**Comment by JJ** [comment]
@mariosky it's this file: https://github.com/JJ/2019-concurrent-ea-gecco/blob/master/concurrent-EvoStar-2019.Rnw Change the name and use ACM format

**Comment by mariosky** [comment]
Done!  @JJ please check it out and close at will.

**Comment by JJ** [comment]
OK, will do.
